### ISSUE TITLE
How to secure routes without updates overwriting this security

### ISSUE THREAD

**Issue by murfett-au** [MatviiB/scheduler#5]
I wish to restrict who can use your wonderful app - how do you recommend I do this?

I could add to the MatviiB\Scheduler\Controllers\SchedulerController the:
```
    public function __construct() {
        $this->middleware('auth');
    }
```
and include a check at the start of each method:
   ```
 public function index()
    {
        $user = \Auth::user();
        if (\App\Lib\Common\Permission::hasPermissionsToPerformThisAction($user->id, 'view_scheduled_tasks') {
```

but I don't want to edit your files in case you update them.

I could remove your routes by deleting/editing the file:
vendor\matviib\scheduler\src\routes\web.php
but this is also in the vendor folder, so I don't want to touch it.

I CAN safely change stuff in the config/scheduler.php file but it only contains a place to define the url prefix for the routes, not a place to disable them completely. I don't want to disable the scheduler by setting SCHEDULER_ENABLED to false, as I want to secure the routes, not disable the function.

I could override your SchedulerController class with a app\Http\Controllers\MySchedulerController.php class - but the 
`$controller = 'MatviiB\\Scheduler\\Controllers\\SchedulerController';`
in
`vendor/matviib/scheduler/src/routes/web.php`
Is also defined inside the vendor folder so is subject to updates.

The only other file deployed using publish was `app/Console/CronTasksList.php` and it does not contain a place to secure the routes (that I can see).

Do you have a recommended way?

**Comment by MatviiB** [comment]
https://github.com/spatie/laravel-permission

maybe

**Comment by murfett-au** [comment]
I don't think this would help (I already have user-roles and role-permission tables and use Laravel gates to manage my app security although I did not use the app you kindly linked to).

The issue is how do I check the security on your routes in a file that won't be overwritten in an update?

**Comment by MatviiB** [comment]
you should use your gates before your user will go through it. i mean in view you need 

@if (user->canMAnageScheduledTasks())
    `<a href="{{ route('scheduler.index') }}">Scheduler</a>`
@endif

**Comment by murfett-au** [comment]
I agree this is a step forward, and would not show to link for people to click, but does it secure the route? I mean does it prevent someone entering the url into their browser to access the page (if they know what the route url is)?

**Comment by MatviiB** [comment]
Ok. Hack)

Config -> scheduler -> URL 
md5(time());

**Comment by MatviiB** [comment]
This will not work. It's a joke. Maybe you can create the middleware for this? And put it to Kernel

**Comment by murfett-au** [comment]
The way I do this in my Laravel apps is to put middleware in the constructor of my controller like this:
```
    class ReportController extends Controller {
    /**
     * Instantiate a new class instance.
    */
    public function __construct() {
        $this->middleware('auth');
    }
    ...
    ...
```

then in each function I check a particular permission:
```
    public function displayReportOne($parameters) {
      $loggedInUser = \Auth::user();// will always be a user as we have auth middleware in constructor.
      if \App\Lib\Common\Permissions::userCan($loggedInUser->id,'reports_display');
    }
```

Or you can put the permission on the route itself inbside web.php. This is all standard laravel way to do it, but I can modify neither the route definition nor the controller in your scheduler.

I am grateful for the functionality, and can always just copy your routes across into my own web.php, but I thought I would point out how this could be done with more security in mind.

Thanks for the code!
