### ISSUE TITLE
Update View Files

### ISSUE THREAD

**Issue by alr2413** [MatviiB/scheduler#8]
Please update
`@if(env('SCHEDULER_ENABLED'))`
to 
`@if(config('scheduler.enabled'))`
in all viewable files.

Thanks.

**Comment by MatviiB** [comment]
yep, you can create PR

**Comment by alr2413** [comment]
Ok. 
I have created a pull request.
thanks.

**Comment by alr2413** [comment]
This problem has been fixed in the pull request #9.
Thanks
